name: Documenter
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:

  docs:
      runs-on: ubuntu-latest
      steps:
        - name: Install doc dependencies
          run: julia --project=. instantiate_environment.jl
          working-directory: docs
        - uses: actions/checkout@v4
        - uses: julia-actions/julia-buildpkg@latest
        - uses: julia-actions/julia-docdeploy@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
